picker:
  dataset: JP
  ckpts_dir: /mnt/lustre/home/sinoue/research_cqr/ckpts/
  lr: 2e-3
  eps: 1e-8
  ignore_index: -100
  num_epochs: 25
  dev_interval: 200
  accumulation_steps: 1
  benchmark: True
  load_premodel: False

writer:
  dataset: JP
  ckpts_dir: /mnt/lustre/home/sinoue/research_cqr/ckpts/
  lr: 2e-5
  eps: 1e-8
  weight_decay: 0.01
  warm_up_ratio: 0.0
  ignore_index: -100
  num_epochs: 70
  dev_interval: 400
  accumulation_steps: 2
  benchmark: True
  load_premodel: False

jointmodel:
  dataset: JP
  ckpts_dir: /mnt/lustre/home/sinoue/research_cqr/ckpts/
  lr: 2e-5
  eps: 1e-8
  weight_decay: 0.01
  warm_up_ratio: 0.0
  ignore_index: -100
  num_epochs: 70
  dev_interval: 400
  accumulation_steps: 2
  loss_weight: 1
  benchmark: True
  load_premodel: False