name: JP
lang: ja
data_root: data/processed/CANARD
pretrained_model: sonoisa/t5-base-japanese
batch_size: {train: 6, dev: 6, test: 16}
shuffle: {train: True, dev: False, test: False}
num_workers: 2
dialog_length: 400
gold_length: 100
sp_token1: "[X1]"
sp_token2: "[X2]"
num_added_token: 1
len_dialog: 400
len_query: 100
label_type: defined
threshold: 0
tokenizer: ???